# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  solution: './EventBus.InProcess.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  tests: './tests/EventBus.InProcess.Tests/EventBus.InProcess.Tests.csproj'
  projectName: 'EventBus.InProcess'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Unit testing'
  inputs:
    command: 'test'
    projects: '$(tests)'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'


- task: PublishCodeCoverageResults@1
  displayName: 'Publish coverage'
  inputs:
    summaryFileLocation: '$(Build.SourcesDirectory)/TestResults/Coverage/*cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/TestResults/Coverage'
    codecoverageTool: 'cobertura'

